#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

currentbranch=$(git branch | grep \* | cut -d ' ' -f2)
git checkout develop
git pull
git merge $currentbranch
git checkout $currentbranch
